/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'status' : BookingStatus,
  'serviceName' : string,
  'userId' : Principal,
  'date' : string,
  'createdAt' : Time,
  'time' : string,
  'problemNotes' : string,
  'address' : string,
  'serviceId' : bigint,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export interface FeaturedService {
  'id' : bigint,
  'categoryId' : bigint,
  'name' : string,
  'currency' : string,
  'rating' : number,
  'priceMax' : bigint,
  'priceMin' : bigint,
  'reviewCount' : bigint,
}
export type Principal = Principal;
export type ProviderStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Review {
  'id' : bigint,
  'serviceName' : string,
  'bookingId' : bigint,
  'userId' : Principal,
  'createdAt' : Time,
  'comment' : string,
  'rating' : bigint,
  'serviceId' : bigint,
}
export interface ServiceCategory {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'iconName' : string,
}
export interface ServiceProvider {
  'id' : bigint,
  'categoryId' : bigint,
  'status' : ProviderStatus,
  'userId' : Principal,
  'name' : string,
  'phone' : string,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'applyAsProvider' : ActorMethod<[string, string, bigint], bigint>,
  'approveProvider' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelBooking' : ActorMethod<[bigint], undefined>,
  'createBooking' : ActorMethod<
    [bigint, string, string, string, string, string],
    bigint
  >,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllProviders' : ActorMethod<[], Array<ServiceProvider>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getCallerReviews' : ActorMethod<[], Array<Review>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeaturedServices' : ActorMethod<[], Array<FeaturedService>>,
  'getOwnBookings' : ActorMethod<[], Array<Booking>>,
  'getReviewsForService' : ActorMethod<[bigint], Array<Review>>,
  'getServiceCategories' : ActorMethod<[], Array<ServiceCategory>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loginWithEmail' : ActorMethod<[string, string], boolean>,
  'loginWithPhone' : ActorMethod<[string, string], boolean>,
  'register' : ActorMethod<[string, string, string, string], undefined>,
  'rejectProvider' : ActorMethod<[bigint], undefined>,
  'rescheduleBooking' : ActorMethod<[bigint, string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitReview' : ActorMethod<
    [bigint, bigint, string, bigint, string],
    bigint
  >,
  'updateBookingStatus' : ActorMethod<[bigint, BookingStatus], undefined>,
  'updateProfile' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];