/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Principal = IDL.Principal;
export const Time = IDL.Int;
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookingStatus,
  'serviceName' : IDL.Text,
  'userId' : Principal,
  'date' : IDL.Text,
  'createdAt' : Time,
  'time' : IDL.Text,
  'problemNotes' : IDL.Text,
  'address' : IDL.Text,
  'serviceId' : IDL.Nat,
});
export const ProviderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const ServiceProvider = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'status' : ProviderStatus,
  'userId' : Principal,
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'serviceName' : IDL.Text,
  'bookingId' : IDL.Nat,
  'userId' : Principal,
  'createdAt' : Time,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
  'serviceId' : IDL.Nat,
});
export const FeaturedService = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'name' : IDL.Text,
  'currency' : IDL.Text,
  'rating' : IDL.Float64,
  'priceMax' : IDL.Nat,
  'priceMin' : IDL.Nat,
  'reviewCount' : IDL.Nat,
});
export const ServiceCategory = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'iconName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'applyAsProvider' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
  'approveProvider' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelBooking' : IDL.Func([IDL.Nat], [], []),
  'createBooking' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllProviders' : IDL.Func([], [IDL.Vec(ServiceProvider)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeaturedServices' : IDL.Func([], [IDL.Vec(FeaturedService)], ['query']),
  'getOwnBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getReviewsForService' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'getServiceCategories' : IDL.Func([], [IDL.Vec(ServiceCategory)], ['query']),
  'getUserProfile' : IDL.Func([Principal], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginWithEmail' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'loginWithPhone' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'register' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'rejectProvider' : IDL.Func([IDL.Nat], [], []),
  'rescheduleBooking' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitReview' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
  'updateProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Principal = IDL.Principal;
  const Time = IDL.Int;
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookingStatus,
    'serviceName' : IDL.Text,
    'userId' : Principal,
    'date' : IDL.Text,
    'createdAt' : Time,
    'time' : IDL.Text,
    'problemNotes' : IDL.Text,
    'address' : IDL.Text,
    'serviceId' : IDL.Nat,
  });
  const ProviderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const ServiceProvider = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'status' : ProviderStatus,
    'userId' : Principal,
    'name' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'serviceName' : IDL.Text,
    'bookingId' : IDL.Nat,
    'userId' : Principal,
    'createdAt' : Time,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
    'serviceId' : IDL.Nat,
  });
  const FeaturedService = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'name' : IDL.Text,
    'currency' : IDL.Text,
    'rating' : IDL.Float64,
    'priceMax' : IDL.Nat,
    'priceMin' : IDL.Nat,
    'reviewCount' : IDL.Nat,
  });
  const ServiceCategory = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'iconName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'applyAsProvider' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
    'approveProvider' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelBooking' : IDL.Func([IDL.Nat], [], []),
    'createBooking' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllProviders' : IDL.Func([], [IDL.Vec(ServiceProvider)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeaturedServices' : IDL.Func([], [IDL.Vec(FeaturedService)], ['query']),
    'getOwnBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getReviewsForService' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'getServiceCategories' : IDL.Func(
        [],
        [IDL.Vec(ServiceCategory)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([Principal], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginWithEmail' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'loginWithPhone' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'register' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'rejectProvider' : IDL.Func([IDL.Nat], [], []),
    'rescheduleBooking' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitReview' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
    'updateProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };